using DevBase.Generics;

namespace DevBase.Format.Structure
{
    public class LrcObject
    {
        private string _artist; //sänger
        private string _album; //album
        private string _title; //songname
        private string _author; //songschreiber
        private string _by; //Lyrics ersteller
        private int _offset; //offset
        private string _re; //Lyrics generated by
        private string _version; //FormatVersion

        private AList<LyricElement> _lyrics; //Lyrics

        public LrcObject() { }

        public LrcObject(string artist, string album, string title, string author, string by, int offset, string re, string version, AList<LyricElement> lyrics)
        {
            _artist = artist;
            _album = album;
            _title = title;
            _author = author;
            _by = by;
            _offset = offset;
            _re = re;
            _version = version;
            _lyrics = lyrics;
        }

        public string Artist
        {
            get => this._artist;
            set => this._artist = value;
        }

        public string Album
        {
            get => this._album;
            set => this._album = value;
        }

        public string Title
        {
            get => this._title;
            set => this._title = value;
        }

        public string Author
        {
            get => this._author;
            set => this._author = value;
        }

        public string By
        {
            get => this._by;
            set => this._by = value;
        }

        public int Offset
        {
            get => this._offset;
            set => this._offset = value;
        }

        public string Re
        {
            get => this._re;
            set => this._re = value;
        }

        public string Version
        {
            get => this._version;
            set => this._version = value;
        }

        public AList<LyricElement> Lyrics
        {
            get => this._lyrics;
            set => this._lyrics = value;
        }
    }
}
