using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DevBase.Generic;

namespace DevBaseFormat.Structure
{
    public class LrcObject
    {
        private string _artist; //sänger
        private string _album; //album
        private string _title; //songname
        private string _author; //songschreiber
        private string _by; //Lyrics ersteller
        private int _offset; //offset
        private string _re; //Lyrics generated by
        private string _version; //FormatVersion

        private GenericList<LyricElement> _lyrics; //Lyrics

        public LrcObject() { }

        public string Artist
        {
            get => _artist;
            set => _artist = value;
        }

        public string Album
        {
            get => _album;
            set => _album = value;
        }

        public string Title
        {
            get => _title;
            set => _title = value;
        }

        public string Author
        {
            get => _author;
            set => _author = value;
        }

        public string By
        {
            get => _by;
            set => _by = value;
        }

        public int Offset
        {
            get => _offset;
            set => _offset = value;
        }

        public string Re
        {
            get => _re;
            set => _re = value;
        }

        public string Version
        {
            get => _version;
            set => _version = value;
        }

        public GenericList<LyricElement> Lyrics
        {
            get => _lyrics;
            set => _lyrics = value;
        }
    }
}
